name: 'Delete unchanged cpp files'
inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
  path:
    description: 'path to delete'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set ownership
      if: inputs.shell == 'bash'
      shell: ${{ inputs.shell }}
      run: |
        # https://github.com/actions/runner/issues/2033
        # this is to fix GIT not liking owner of the checkout dir
        chown -R $(id -u):$(id -g) $PWD

    - name: Get changed cpp files
      id: changed-cpp-files
      uses: tj-actions/changed-files@v42
      with:
        separator: ";"
        quotepath: false
        safe_output: false
        files: |
          **.cpp
          **.cc
          **.cxx

    - name: Delete unchanged cpp files
      env:
        TARGET_PATH: ${{ inputs.path }}
        ALL_CHANGED_FILES: ${{ steps.changed-cpp-files.outputs.all_changed_files }}
        RUN_SCRIPT: ${{ inputs.shell == 'pwsh' && 'RemoveUnchangedCppFile.ps1' || 'remove_unchanged_cpp_file.sh'}}
      shell: ${{ inputs.shell }}
      run: .github/actions/delete-unchanged-cpp-files/${{ env.RUN_SCRIPT }}

