name: Test your docker package

on:
  workflow_dispatch:
    inputs:
      publish_docker:
        type: boolean
        default: true
        description: publish your docker

jobs:
    convert-repo-to-lowercase:
      runs-on: ubuntu-latest
      outputs:
        repo_lowercase: ${{ steps.github-repo-lowercase.outputs.REPO_LC }}
      steps:
        - name: Convert GITHUB_REPOSITORY lowercase
          id: github-repo-lowercase
          run: |
            echo "REPO_LC=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

    publish-docker:
      if: inputs.publish_docker
      uses: ./.github/workflows/publish-docker.yml

    check-loser-homework:
      needs: [convert-repo-to-lowercase, publish-docker]
      uses: ./.github/workflows/check-loser-homework.yml
      with:
        docker_namespaces: ${{ needs.convert-repo-to-lowercase.outputs.repo_lowercase }}
